### ISSUE TITLE
Whitelist all incoming requests

### ISSUE THREAD

**Issue by mre** [urbanairship/frock#6]
Hi,

I'm using frock to run some integration tests for a new project.
For that I created a Docker container like so:

```
FROM node:5

RUN npm install frock-static frock-proxy
RUN npm install -g frock
WORKDIR config
EXPOSE 8080
```

I built it with `docker build -t urbanairship/frock .`

To start the container I run

    docker run -it --rm -v `pwd`:/config -p 8080:8080 urbanairship/frock frock

(The -v part is for mounting the frockfile.json from the README into the appropriate location inside my container)

After that I tested if it works with: `curl docker.local:8080/api/segments` where `docker.local` is the IP address of my docker host (I'm using boot2docker on OSX).

I got the following response:
`info frock/core-httpsever: access from non-whitelisted, or from blacklisted address`

After reading the documentation I found an option to circumvent this by putting the following inside my frockfile.json: `"connection": { "whitelist": ["192.168.0.1/8"] }`
This will whitelist all IP addresses as far as I can tell.
Since frock will only be visible to the linked containers this is okay and very useful for integration testing. 

 What do you think about these two friendly suggestions?
1. Please add a Dockerfile to the project. It should be pretty similar to the one above. This way everybody can just run it right away without installing any node dependencies.
2. Maybe add a comment in the docs on how to whitelist all IP addresses.

This would make it much easier for new users to get started.
Thanks for your tool. It's nicely done. Especially the auto-reloading of the config file. :smiley:

**Comment by clancychilds** [comment]
The 192.168.0.1/8 subnet will only allow access to IPs where the first octet is 192.
I have used 0.0.0.0/0 for a fully open whitelist.

**Comment by mre** [comment]
Ouch. Thanks for the correction :sweat_smile:

**Comment by fardog** [comment]
I'll definitely look to improve the documentation in this aspect; the default whitelist was added just to make things a little safer out of the box, but one of the things i've considered is an `--disable-whitelist` CLI flag that you could pass to frock, which disables its default whitelist and makes things open to all addresses; this would be a lot more pleasant than explicitly configuring it in your frockfile for this use, I think.

As for the Dockerfile: I think this would be a good example to have.

I've created issues for these; I've tagged them as "help wanted" if anyone has the time to get to them, but they're also something I should be able to get to in the next week or so:

#7
#8
#9

Thanks for the suggestions! I'm going to close this issue since it seems like the initial problem was resolved, and you can track on the above issues if you'd like to follow along.
